# Preprocessing Scraped Data

Web scraper is currently running on csa2. Data files represent data scraped every hour from the Honolulu HPD [website](http://www4.honolulu.gov/hpdtraffic/MainPrograms/frmMain.asp?sSearch=All+Incidents&sSort=I_tTimeCreate)

In [1]:
%matplotlib inline
import json
import pandas as pd
import os
import googlemaps
import json
import sys  
import matplotlib.pyplot as plt 
import requests
import re

In [8]:
# Convert data files into a Pandas Data Frame
file_names = []
for file in os.listdir('data/'):
    val = int(re.search(r'\d+', file).group())
    if val > 648:
        file_names.append(file)

data_master = []
for file in file_names:
    with open('data/' + file, 'r') as f:
        data = json.loads(f.readline())
        data_master = data_master + data
        
df_master = pd.DataFrame(data_master)
df_master.to_csv('master_dataset_2.csv')  
df_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1350 entries, 0 to 1349
Data columns (total 6 columns):
address     1350 non-null object
area        1350 non-null object
date        1350 non-null object
location    1350 non-null object
time        1350 non-null object
type        1350 non-null object
dtypes: object(6)
memory usage: 63.4+ KB

In [9]:
# Read csv, combine "date" and "time" column to a date object, and sort by "date" column
df = pd.read_csv('master_dataset_2.csv', index_col='Unnamed: 0')
# df = df_master
df['date'] = df['date'].astype(str) + ' ' + df['time']
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values(by='date')
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1350 entries, 579 to 227
Data columns (total 6 columns):
address     1350 non-null object
area        1350 non-null object
date        1350 non-null datetime64[ns]
location    1350 non-null object
time        1350 non-null object
type        1350 non-null object
dtypes: datetime64[ns](1), object(5)
memory usage: 73.8+ KB

In [10]:
# Initialize Google Maps 
api_key = 'AIzaSyCmr-ah82Xzb6uq2jOLlIFgek_CI7Mg4Uw'
gmaps = googlemaps.Client(key=api_key)

In [14]:
# Example calls to Google Maps of highways, highway offramps, and street intersections
result = gmaps.geocode('H2N WAHIAWA OFF, MILILANI, HI')
print(json.dumps(result, indent=4))
# result = gmaps.geocode('INTERSTATE H-2, WAHIAWA, HI')  #This actually gives back the right location
# print(json.dumps(result, indent=4))
# result = gmaps.geocode('KAWAIAHAO ST & SOUTH ST, HONOLULU, HI')
print(json.dumps(result, indent=4))

[
    {
        "types": [
            "locality",
            "political"
        ],
        "geometry": {
            "location": {
                "lng": -158.0152807,
                "lat": 21.4513314
            },
            "viewport": {
                "northeast": {
                    "lng": -157.9924,
                    "lat": 21.4658301
                },
                "southwest": {
                    "lng": -158.0301801,
                    "lat": 21.4262321
                }
            },
            "bounds": {
                "northeast": {
                    "lng": -157.9924,
                    "lat": 21.4658301
                },
                "southwest": {
                    "lng": -158.0301801,
                    "lat": 21.4262321
                }
            },
            "location_type": "APPROXIMATE"
        },
        "place_id": "ChIJ_cVNtwRnAHwRFaLS4aRQi7Y",
        "address_components": [
            {
                "types": [
                    "locality",
                    "political"
                ],
                "short_name": "Mililani",
                "long_name": "Mililani"
            },
            {
                "types": [
                    "administrative_area_level_2",
                    "political"
                ],
                "short_name": "Honolulu County",
                "long_name": "Honolulu County"
            },
            {
                "types": [
                    "administrative_area_level_1",
                    "political"
                ],
                "short_name": "HI",
                "long_name": "Hawaii"
            },
            {
                "types": [
                    "country",
                    "political"
                ],
                "short_name": "US",
                "long_name": "United States"
            },
            {
                "types": [
                    "postal_code"
                ],
                "short_name": "96789",
                "long_name": "96789"
            }
        ],
        "formatted_address": "Mililani, HI 96789, USA",
        "partial_match": true
    }
]
[
    {
        "types": [
            "locality",
            "political"
        ],
        "geometry": {
            "location": {
                "lng": -158.0152807,
                "lat": 21.4513314
            },
            "viewport": {
                "northeast": {
                    "lng": -157.9924,
                    "lat": 21.4658301
                },
                "southwest": {
                    "lng": -158.0301801,
                    "lat": 21.4262321
                }
            },
            "bounds": {
                "northeast": {
                    "lng": -157.9924,
                    "lat": 21.4658301
                },
                "southwest": {
                    "lng": -158.0301801,
                    "lat": 21.4262321
                }
            },
            "location_type": "APPROXIMATE"
        },
        "place_id": "ChIJ_cVNtwRnAHwRFaLS4aRQi7Y",
        "address_components": [
            {
                "types": [
                    "locality",
                    "political"
                ],
                "short_name": "Mililani",
                "long_name": "Mililani"
            },
            {
                "types": [
                    "administrative_area_level_2",
                    "political"
                ],
                "short_name": "Honolulu County",
                "long_name": "Honolulu County"
            },
            {
                "types": [
                    "administrative_area_level_1",
                    "political"
                ],
                "short_name": "HI",
                "long_name": "Hawaii"
            },
            {
                "types": [
                    "country",
                    "political"
                ],
                "short_name": "US",
                "long_name": "United States"
            },
            {
                "types": [
                    "postal_code"
                ],
                "short_name": "96789",
                "long_name": "96789"
            }
        ],
        "formatted_address": "Mililani, HI 96789, USA",
        "partial_match": true
    }
]

In [5]:
# Mapped first 2175
# df = df.ix[2175:]
# df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2307 entries, 2175 to 666
Data columns (total 6 columns):
address     2307 non-null object
area        2307 non-null object
date        2307 non-null datetime64[ns]
location    2307 non-null object
time        2307 non-null object
type        2307 non-null object
dtypes: datetime64[ns](1), object(5)
memory usage: 126.2+ KB

In [11]:
# Store longitude and latitude data returned from Google Maps to dataframe 
# df_temp = df.head(2500)
# List of dictionaries
d = []
errors = []
# Counter for how many datapoints have been processed
count = 0
for idx, row in df.iterrows():
    count += 1
    try :
        change = row['address'].split(' ')
        for i in range(len(change)):
            if change[i][-1] == 'X':
                change[i] = change[i][:-1] + '0'
            if change[i].find('&') != -1:
                toDelete = change[i].find('&')
                change[i] = change[i][:toDelete] + ' & ' + change[i][toDelete+1:]
            if change[i].find('/') != -1:
                toDelete = change[i].find('/')
                change[i] = change[i][:toDelete] + ' & ' + change[i][toDelete+1:] + ' ST'
            if change[i].find(';') != -1:
                toDelete = change[i].find(';')
                change[i] = change[i][:toDelete] + '' + change[i][toDelete+1:]
        if change[0] == 'KAM':
            change[0] = 'KAMEHAMEHA HWY'
        if change[0][0] == 'H' and len(change[0]) == 3:
            change[0] = 'INTERSTATE H-' + change[0][1]
            if len(change) > 1:
                if change[2] == 'OFF' or change[2] == 'ON' or change[2] == 'FWY':
                    del change[2]

        elif len(change) > 1 and change[1][0] == 'H' and len(change[1]) == 3:
            change[1] = 'INTERSTATE H-' + change[1][1]
            if change[2] == 'OFF' or change[2] == 'ON' or change[2] == 'FWY':
                del change[2]
            del change[0]


        # Convert street, city, and state to a string representation
        add = ' '.join(change)
        address = [add, row['area'], 'HI'] #add=row['address']
        if address[1] == 'AIRPORT':
            if address[0] == 'INTERSTATE H-1':
                address[0] = '300 ROGERS BLVD'
            address[1] = 'HONOLULU'
        if address[1] == 'HOKULANI' or address[1] == 'DOWNTOWN' or address[1] == '':
            address[1] = 'HONOLULU'
        if address[1] == 'SUNSET':
            del address[1]
        if address[1] == 'MOANALUA V':
            address[1] = 'MOANALUA FWY'
            del address[0]

        address = ', '.join(address)
        result = gmaps.geocode(address)
    
        # Create a dictionary from results
        loc = result[0]['geometry']['location']
        point = {'index': idx, 'latitude':loc['lat'], 'longitude':loc['lng']}
        d.append(point)
        
        # Pickles a dataframe every 100 iteration so that we don't lose data if an error occurs
        if count % 100 == 0 or count == len(df):
            print('Iteration {}'.format(count))
            df_loc = pd.DataFrame(d)
            df_loc.to_pickle('location_2.pkl')
    except KeyboardInterrupt:
        print('Exiting...')
        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)
    except: 
        errors.append(idx)
#         print('Error: ' + str(address) + ' at index ' + str(idx))
        continue

Iteration 100
Iteration 200
Iteration 300
Iteration 400
Iteration 700
Iteration 800
Iteration 900
Iteration 1000
Iteration 1100
Iteration 1200
Iteration 1300
Iteration 1350

In [12]:
df_loc = pd.read_pickle('location_2.pkl')
df_loc = df_loc.set_index('index')
df_loc.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1258 entries, 579 to 227
Data columns (total 2 columns):
latitude     1258 non-null float64
longitude    1258 non-null float64
dtypes: float64(2)
memory usage: 29.5 KB

In [13]:
# df_subset = df.head(len(df_loc))
df_subset = df.join(df_loc)
df_subset.head()

,address,area,date,location,time,type,latitude,longitude
579,S BERETANIA ST&KEEAUMOKU; ST,HONOLULU,2016-11-29 16:42:28,,4:42:28 PM,TRAFFIC NUISANCE OR PARKING VIOLATION,21.300233,-157.839508
578,FORT WEAVER RD&GEIGER; RD,EWA BEACH,2016-11-29 16:44:30,,4:44:30 PM,MOTOR VEHICLE COLLISION,21.333712,-158.023057
577,276X TANTALUS DR,MAKIKI,2016-11-29 16:46:22,,4:46:22 PM,MOTOR VEHICLE COLLISION,21.317293,-157.833107
576,MISSION LN&QUEEN; ST,HONOLULU,2016-11-29 16:49:15,KAWAIAHAO CHURCH SCHOOL,4:49:15 PM,MOTOR VEHICLE COLLISION,21.302845,-157.858655
575,PACIFIC HTS RD&PAUOA; RD,PUNCHBOWL,2016-11-29 16:54:05,,4:54:05 PM,TRAFFIC NUISANCE OR PARKING VIOLATION,NaN,NaN

In [14]:
df_subset.to_pickle('master_location_2.pkl')

In [13]:
df_subset['hour'] = df_subset.date.apply(lambda d: d.hour) 
df_subset.head()

,address,area,date,location,time,type,latitude,longitude,hour
2175,37X HALELOA PL,AINA HAINA,2016-11-18 09:09:07,,9:09:07 AM,MOTOR VEHICLE COLLISION,21.291203,-157.723040,9
2174,142X HONOKAHUA ST,HAWAII KAI,2016-11-18 09:11:39,,9:11:39 AM,MOTOR VEHICLE COLLISION,21.309007,-157.671856,9
2173,46050X KAM HWY,KANEOHE,2016-11-18 09:15:14,HEEIA KEA BOAT HARBO,9:15:14 AM,TRAFFIC NUISANCE OR PARKING VIOLATION,21.456264,-157.827796,9
2172,45099X LIKELIKE HWY,KANEOHE,2016-11-18 09:18:30,WILSON TUNNEL D4 N,9:18:30 AM,TRAFFIC NUISANCE OR PARKING VIOLATION,21.394319,-157.811448,9
2171,81X KAPIOLANI BLVD,HONOLULU,2016-11-18 09:22:44,MERCEDES BENZ DEALERSHIP,9:22:44 AM,MOTOR VEHICLE COLLISION,21.300171,-157.853608,9

In [ ]:
df_subset['day'] = df_subset.date.apply(lambda d: d.day)